### ISSUE TITLE
Проблема с кодировкой?

### ISSUE THREAD

**Issue by Akaineko-astasi** [Fenrir-Game-Project/rAthena-in-Russian#1]

**Comment by roFenrir** [comment]
Где?

**Comment by az187i** [comment]
в репе кириллица некорректно отображается, но я думаю это больше вопрос в кодировке заливаемых файлов и особенностях гита

вечером посмотрю что к чему, если до этого не решите проблему

**Comment by roFenrir** [comment]
Файлы в кодировке Windows 1251, дэфолтной для rAthena. Но гит не правильно показывает. У меня SourceTree  под MAC то же неправильно показывает. Но с самими файлами всё ок.
Можно конечно конвертнуть файлы но потом будут танцы с бубном что бы rAthena их нормально кушала.

**Comment by Xsoid** [comment]
Родные rAthena скрипты в кодировке UTF-8 но там нет кириллицы :) Если оставить кодировку UTF-8 то сервер её будет не правильно показывать. Если перекодировать файлы в Windows 1251 то кириллица отображается сервером корректно.
